#! /usr/bin/env python3

import sys
import time
import json
import requests

from robomaze.astar import AStar

URL = "https://robomaze.skadge.org/"

if __name__ == '__main__':

    if len(sys.argv) != 2:
        print("Usage: pyrobomaze <name of robot>")
        sys.exit()

    name = sys.argv[1]

    next_move = "E"

    astar = AStar()

    while 1:
        response = requests.get(URL + f"move/{name}/{next_move}")

        obstacles = json.loads(response.text)[1]

        next_move = astar.get_next_move(obstacles)

        time.sleep(0.25)



